apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: frontend-nginx-config
      containers:
      - name: frontend
        image: tuacr.azurecr.io/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VUE_APP_AUTH_API_URL
          value: "http://auth-api.dev.svc.cluster.local:8081"
        - name: VUE_APP_USERS_API_URL
          value: "http://users-api.dev.svc.cluster.local:8080"
        - name: VUE_APP_TODOS_API_URL
          value: "http://todos-api.dev.svc.cluster.local:8082"
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend 