trigger:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-variables

stages:
- stage: Build
  displayName: 'Build Frontend'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.17.0'
    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build Node.js Application'
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: frontend
        dockerfile: frontend/Dockerfile
        containerRegistry: ACR
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: 'Deploy Frontend'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to AKS'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'dev-aks'
        namespace: 'dev'
        command: 'apply'
        arguments: '-f frontend/k8s/dev/deployment.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        dockerRegistryEndpoint: 'ACR' 