trigger:
  branches:
    include:
    - main
  paths:
    include:
    - todos-api/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-variables

stages:
- stage: Build
  displayName: 'Build TODOs API'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
    - script: |
        cd todos-api
        npm install
        npm run build
      displayName: 'Build TODOs API'
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: todos-api
        dockerfile: todos-api/Dockerfile
        containerRegistry: acr-connection
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: 'Deploy TODOs API'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to AKS'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'k8s-dev-connection'
        namespace: 'dev'
        command: 'apply'
        arguments: '-f todos-api/k8s/dev/deployment.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        dockerRegistryEndpoint: 'acr-connection' 