apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: tuacr.azurecr.io/auth-api:latest
        ports:
        - containerPort: 8081
        env:
        - name: AUTH_API_PORT
          value: "8081"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        - name: USERS_API_ADDRESS
          value: "http://users-api:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: auth-api 