apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: $(ACR_NAME).azurecr.io/auth-api:$(Build.BuildId)
        ports:
        - containerPort: 8081
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: auth-api 