apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
      - name: log-message-processor
        image: tuacr.azurecr.io/log-message-processor:latest
        ports:
        - containerPort: 8083
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: log-message-processor
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: log-message-processor 