apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: tuacr.azurecr.io/users-api:rebuild
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8083
  selector:
    app: users-api