trigger:
  branches:
    include:
    - main
  paths:
    include:
    - auth-api/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-variables

stages:
- stage: Build
  displayName: 'Build Auth API'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    steps:
    - task: GoTool@0
      inputs:
        version: '1.18.2'
    - script: |
        export GO111MODULE=on
        cd auth-api
        go mod init github.com/bortizf/microservice-app-example/tree/master/auth-api
        go mod tidy
        go build
      displayName: 'Build Go Application'
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: auth-api
        dockerfile: auth-api/Dockerfile
        containerRegistry: ACR
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: 'Deploy Auth API'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to AKS'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'dev-aks'
        namespace: 'dev'
        command: 'apply'
        arguments: '-f auth-api/k8s/dev/deployment.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        dockerRegistryEndpoint: 'ACR' 