trigger:
  branches:
    include:
      - main
  paths:
    include:
      - auth-api/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-variables

stages:
- stage: Build
  displayName: 'Build Auth API'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    steps:
    - task: GoTool@0
      inputs:
        version: '1.18'
      displayName: 'Install Go'

    - script: |
        # Diagnóstico: Verifica que auth-api existe
        echo "Verificando archivos en el workspace..."
        ls -la $(System.DefaultWorkingDirectory)

        # Configurar GOPATH y estructura de directorios
        export GOPATH=/home/vsts/go
        export GOBIN=$GOPATH/bin
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/microservice-app-example/auth-api

        # Copiar código al GOPATH correcto
        cp -r $(System.DefaultWorkingDirectory)/auth-api/* $GOPATH/src/github.com/microservice-app-example/auth-api/

        # Instalar dep
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        export PATH=$PATH:$GOBIN

        # Build
        cd $GOPATH/src/github.com/microservice-app-example/auth-api
        dep ensure
        go build -o auth-api

        # Copiar el binario de vuelta
        cp auth-api $(System.DefaultWorkingDirectory)/auth-api/
      displayName: 'Build Go App'

    - task: Docker@2
      inputs:
        containerRegistry: acr-connection
        repository: auth-api
        command: buildAndPush
        Dockerfile: auth-api/Dockerfile
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: 'Deploy Auth API'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to AKS'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'k8s-dev-connection'
        namespace: 'dev'
        command: 'apply'
        arguments: '-f auth-api/k8s/dev/deployment.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        dockerRegistryEndpoint: 'acr-connection'
