- stage: Build
  displayName: 'Build Auth API'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    steps:
    - task: GoTool@0
      inputs:
        version: '1.18'
      displayName: 'Install Go'

    - script: |
        cd auth-api
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
        go build
      displayName: 'Build Go App'

    - task: Docker@2
      inputs:
        containerRegistry: acr-connection
        repository: auth-api
        command: buildAndPush
        Dockerfile: auth-api/Dockerfile
        tags: |
          $(Build.BuildId)
          latest