trigger:
  branches:
    include:
    - main
  paths:
    include:
    - users-api/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-variables

stages:
- stage: Build
  displayName: 'Build Users API'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '8'
        jdkArchitectureOption: 'x64'
    - script: |
        cd users-api
        ./mvnw clean install
      displayName: 'Build Java Application'
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: users-api
        dockerfile: users-api/Dockerfile
        containerRegistry: ACR
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: 'Deploy Users API'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy to AKS'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'dev-aks'
        namespace: 'dev'
        command: 'apply'
        arguments: '-f users-api/k8s/dev/deployment.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        dockerRegistryEndpoint: 'ACR' 