trigger:
  branches:
    include:
    - develop
    - main
  paths:
    include:
    - users-api/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: dev-variables
  - name: dockerRegistry
    value: '$(ACR_NAME).azurecr.io'
  - name: imageName
    value: 'users-api'
  - name: tag
    value: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Build
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'users-api/pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
    
    - task: Docker@2
      inputs:
        command: 'build'
        repository: '$(imageName)'
        dockerfile: 'users-api/Dockerfile'
        tags: '$(tag)'
        containerRegistry: '$(dockerRegistry)'

- stage: DeployDev
  displayName: 'Deploy to Development'
  condition: succeeded()
  jobs:
  - deployment: Deploy
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'k8s-dev-connection'
              namespace: 'dev'
              manifests: 'users-api/k8s/dev/*.yaml'
              imagePullSecrets: 'acr-secret'
