apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
      - name: todos-api
        image: $(ACR_NAME).azurecr.io/todos-api:$(Build.BuildId)
        ports:
        - containerPort: 8082
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: AUTH_SERVICE_URL
          value: "http://auth-api:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: todos-api 