trigger:
  branches:
    include:
    - main
  paths:
    include:
    - todos-api/*

variables:
- group: dev-variables

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'

    - script: |
        cd todos-api
        npm install
        npm test
      displayName: 'npm install and test'

    - task: Docker@2
      inputs:
        containerRegistry: 'ACR'
        repository: 'todos-api'
        command: 'buildAndPush'
        Dockerfile: 'todos-api/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  jobs:
  - deployment: Deploy
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'dev-aks'
              namespace: 'dev'
              manifests: 'todos-api/k8s/dev/*.yaml'
              containers: '$(ACR_NAME).azurecr.io/todos-api:$(Build.BuildId)' 